GET http://localhost:3000/
###
POST http://localhost:3000/users

###
GET http://localhost:3000/users
###
PATCH http://localhost:3000/users/me
###
PUT http://localhost:3000/users/62eed6826a7cfcdf9e354552

